#!/bin/bash
# Prints count of new mails in the maildir.

if [ ! -d "$NOTIFY_MAILDIR" ]; then
  exit 1
fi

new=`ls $NOTIFY_MAILDIR  | wc -w`

# Short circuit if not enough emails.
if (( new < 10 )); then
  exit 0
fi

color="#777777"

if (( new > 100 )); then
  color="red"
elif (( new > 10 )); then
  color="yellow"
elif (( new > 0 )); then
  color="#ffffff"
fi

echo "<span color='#777777'>📫  </span><span color='$color'>" $new "</span>"
