#!/bin/bash

ACTIVE_WINDOW=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2 | cut -c -30)

if [[ "${ACTIVE_WINDOW}" != "" ]]; then
  echo "${ACTIVE_WINDOW}"
  echo "${ACTIVE_WINDOW}"
  echo ""
fi
