#!/bin/bash

ACTIVE_WINDOW=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW \
    | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2 | cut -c -30 \
    | iconv -c -f utf-8 -t ascii)

if [[ "${ACTIVE_WINDOW}" != "" ]]; then
  echo "${ACTIVE_WINDOW}"
fi
