alias c='clear'
alias echo='echo -e'
alias lsd='ls -d */'
alias l='ls -alrt'
alias aliases='vim ~/.bash_aliases'
alias apps='sudo /usr/bin/software-center'
alias restart='sudo shutdown now -r'
alias lk='gnome-screensaver-command -l'

alias vimrc='vim ~/.vimrc'
alias d='~/dotfiles/do'
