#!/bin/bash
# Center and resize the active window.

# Determine resolution of the current monitor.
# See https://superuser.com/questions/603528/how-to-get-the-current-monitor-resolution-or-monitor-name-lvds-vga1-etc
## Get screen info
screen1=($(xrandr | grep -w connected | sed 's/primary //' | awk -F'[ +]' '{print $1,$3,$4}' | head -n 1))
screen2=($(xrandr | grep -w connected | sed 's/primary //' | awk -F'[ +]' '{print $1,$3,$4}' | tail -n 1))

## Figure out which screen is to the right of which
if [ ${screen1[2]} -eq 0  ]
then
    right=(${screen2[@]});
    left=(${screen1[@]});
else
    right=(${screen1[@]});
    left=(${screen2[@]});

fi

## Get window position
pos=$(xwininfo -id $(xdotool getactivewindow) | grep "Absolute upper-left X" |
      awk '{print $NF}')

## Which screen is this window displayed in? If $pos
## is greater than the offset of the rightmost screen,
## then the window is on the right hand one
if [ "$pos" -gt "${right[2]}" ]
then
    res=${right[1]}
    echo "${right[0]} : ${right[1]}"
else
    res=${left[1]}
    echo "${left[0]} : ${left[1]}"
fi


width=$(echo $res | awk -Fx '{print $1}')
height=$(echo $res | awk -Fx '{print $2}')

# Setup window to cover .75x of the width and the height.
left=$(( $width / 8 ))
down=$(( $height / 8 ))
winwidth=$(( ( $width * 3 ) / 4 ))
winheight=$(( ( $height * 3 ) / 4 ))

params="0,$left,$down,$winwidth,$winheight"
wmctrl -r :ACTIVE: -e $params
