#!/bin/bash

# Utility script to select a URL from Chrome and Chrome Beta history (via rofi),
# and then open a new browser window with that URL. The browser is passed as the
# first argument to the script.

if [ -z "$1" ]; then
  echo "Pass the browser command as the only argument."
  exit 1
fi


mkdir -p ~/tmp

#if [ ! -e "$localdb" ] || [ ! -z "`find $localdb -mtime +30s`" ] ; then
  cp -f  ~/.config/google-chrome/Default/History ~/tmp/ChromeHistory
  cp -f  ~/.config/google-chrome-beta/Default/History ~/tmp/ChromeBetaHistory
#fi

sqlite3 ~/tmp/ChromeHistory \
  "select title,url from urls order by last_visit_time desc limit 50000" > /tmp/c.h
sqlite3 ~/tmp/ChromeBetaHistory \
  "select title,url from urls order by last_visit_time desc limit 50000" > /tmp/c.b.h

title_url=`(cat /tmp/c.h /tmp/c.b.h | uniq) | rofi -dmenu -i`

if [ -z "$title_url" ] ; then
  exit 0
fi

if [[ $title_url == *"|"* ]]; then
  url=`echo $title_url | cut -f2 -d'|'`
else
  url="http://google.com/search?q=$title_url"
fi

$1 "$url"
