#!/bin/bash
#!/usr/bin/env bash

if [ x"$@" = x"Quit" ]
then
  exit;
fi

tool="xdg-open"
if hash gnome-open 2>/dev/null; then
  tool="gnome-open"
fi

if [ "$@" ] && ! [ "$@" = "Restart" ]; then
  if [[ -d "$@" ]] || [[ -f "$@" ]]; then
    coproc ( $tool "$@"  > /dev/null 2>&1 )
    exec 1>&-
    exit;
  else
    $HOME/.cargo/bin/fd -L -p -j 20 "$@" $HOME
    echo "Restart"
    echo "Quit"
  fi
else
  echo "Enter Query"
fi
