#!/bin/bash

# An unsophisticated script to sync a git repo. I use this to periodically sync
# my notes repository. There's pretty much no error checking, as this script
# is assumed to be running as a daemon on all my machines.
# TODO: Send a mail or something when things break.

if [ "$#" -lt 1 ]
then
  echo "Usage: git-sync.sh <dir> <polling freq>"
  exit 1
fi

polltime="300"
if [ "$#" -ge 2 ]
then
  polltime=$2
fi

cd $1
git rev-parse

if [ "$?" -ne "0" ]; then
   echo "Not in a git repository!";
fi

while true; do
  git pull origin master
  num_changes=`git status --porcelain | wc -l`
  echo "Found $num_changes changes."
  if (( $num_changes > 0)); then
    dt=`date`
    host=`hostname`
    commit="$num_changes files changed from $host at $dt"
    git add -A; git commit -m "$commit"; git push origin master
    echo $commit
  fi
  echo "Sleeping for $polltime seconds."
  sleep $polltime
done
