#!/bin/bash
query="$@"
f="/tmp/howdoi.answer"
howdoi "$query" -n 5 >$f
csplit \
  --suppress-matched \
  --prefix="$f" \
  $f "/--- Answer [1-5] ---/" "{*}"

lines=$(ls /tmp/howdoi.answer0* | xargs wc -l | sed '$d' | awk 'max=="" || data=="" || $1 > max {max=$1 ; data=$2} END{ print max " " data}'a | cut -f1 -d" ")

function cat_with_separator() {
  for f in /tmp/howdoi.answer0[1-5]; do
    cat $f
    printf '\x0f'
  done
}

cat_with_separator | rofi -fullscreen -eh $lines -dmenu -sep '\x0f' -lines 1 | sed '/^$/d' >/tmp/howdoi.answer.selected
copyq copy - </tmp/howdoi.answer.selected
copyq add - </tmp/howdoi.answer.selected
rm /tmp/howdoi*
