#!/bin/bash
# Script that runs when screen is unlocked.
rm -f /tmp/screen-locked

# Revert all emacs buffers. Emacs cannot automatically revert all buffers, since some of
# the fuse mounts I use don't do a good job of exposing updates.
emacsclient -e "(sa/revert-all-buffers)"

# Setup xautolock.
killall xautolock
nohup sh -c \
    'xautolock -time 10 -notify 30 -locker "$HOME/dotfiles/utils/screen-lock"' &

# Clean the desktop
clean=$(echo "no|yes" | \
             rofi -dmenu -p "Clean Desktop? " \
                  -fullscreen -padding 200 -sep '|' -only-match)
if [ "$clean" = "yes" ]; then
  ~/dotfiles/utils/close-windows
fi
