#!/bin/bash
# Script to lock the screen and turn off the display.
# This is called on idle timeout from i3config.

scrot /tmp/screen_locked.png
convert /tmp/screen_locked.png -scale 10% -scale 1000% /tmp/screen_locked2.png
rm -f /tmp/screen_locked.png
echo "`date '+%Y-%m-%d %H:%M'` SCREEN-LOCK" >> ~/purpose-log.txt
touch /tmp/screen-locked

(sleep 10; pgrep i3lock && xset dpms force off) &
i3lock -i /tmp/screen_locked2.png -n; ~/dotfiles/utils/screen-unlock; ~/.dwm/xsetroot.sh
