#!/bin/bash

# TODO: Cache the history files.
mkdir -p ~/tmp

OPTIONS="$HOME/tmp/options.tmp"

# TODO: Fix $PATH in default shell and remove this.
export PATH="$PATH:$HOME/.local/bin"

# Browser Tabs
brotab list | sed --expression='s/^/TAB> /' > $OPTIONS
wmctrl -l | sed --expression='s/^/WIN> /' >> $OPTIONS

echo "------------------------------------" >> $OPTIONS

# Chrome History
cp -f  ~/.config/google-chrome/Default/History ~/tmp/ChromeHistory
sqlite3 ~/tmp/ChromeHistory \
  "select title,url from urls order by last_visit_time desc limit 50000" > ~/tmp/c.h
cat ~/tmp/c.h | uniq | sed --expression='s/^/CHIST> /' >> $OPTIONS

echo "------------------------------------" >> $OPTIONS

# Firefox History

rm ~/tmp/f.h
db_paths=$(find ~/.mozilla/firefox/ -type f -name "places.sqlite" -mindepth 2 -maxdepth 2 2>/dev/null)
for db_path in $db_paths;
do
    # Firefox's bookmarks db is locked when in use so copy it first to a temporary file.
    temp_db="$HOME/tmp/firefox_history-$RANDOM.tmp"
    cp $db_path $temp_db

    sqlite3 "$temp_db" \
      "SELECT title,url from moz_places WHERE visit_count > 0 ORDER BY last_visit_date DESC LIMIT 50000" >> ~/tmp/f.h

    rm $dbPath
done
cat ~/tmp/f.h | uniq | sed --expression='s/^/FHIST> /' >> $OPTIONS

sel=`cat $OPTIONS | rofi -dmenu -i`
mode=`echo $sel | cut -d'>' -f1`

if [[ "$mode" == "WIN" ]]; then
  win=`echo $sel | cut -d' ' -f2`
  wmctrl -i -a $win
elif [[ "$mode" == "TAB" ]]; then
  tab=`echo $sel | cut -d' ' -f2`
  browser_id="${tab:0:2}"
  client=`brotab clients | grep ^$browser_id | cut -f4`
  echo $client
  if [[ "$client" == "firefox" ]]; then
    wmctrl -x -a firefox
  elif [[ "$client" == "chrome/chromium" ]]; then
    wmctrl -x -a google-chrome
  fi
  brotab activate $tab
elif [[ "$mode" == "CHIST" ]]; then
  title_url="${sel:7}"
  if [[ $title_url == *"|"* ]]; then
    url=`echo $title_url | cut -f2 -d'|'`
  else
    url="http://google.com/search?q=$title_url"
  fi
  google-chrome $url
elif [[ "$mode" == "FHIST" ]]; then
  title_url="${sel:7}"
  if [[ $title_url == *"|"* ]]; then
    url=`echo $title_url | cut -f2 -d'|'`
  else
    url="http://google.com/search?q=$title_url"
  fi
  ~/bin/firefox $url
else
  ~/bin/firefox --search "$sel"
fi
