#!/bin/bash

val=`printf "mute\n10\n20\n30\n40\n50\n60\n70\n80\n90\n100" | rofi -dmenu`

if ! [ "$val" = "mute" ]; then
  amixer set Master unmute
fi

amixer set Master $val
notify-send "Volume set to $val"
