#!/bin/bash

val=`printf "mute\n10\n20\n30\n40\n50\n60\n70\n80\n90\n100" | rofi -dmenu`

if [ "$val" = "mute" ]; then
  pactl set-sink-mute @DEFAULT_SINK@ 1
  notify-send "Muted."
  exit 0
fi
pactl set-sink-mute @DEFAULT_SINK@ 0
pactl set-sink-volume @DEFAULT_SINK@ "$val%"
notify-send "Volume set to $val"
