#!/bin/bash
# Change volume from the command line.
# Usage:
#   volume [up|down] [X%|XdB] [mixer]

# The second parameter overrides the mixer selection
# For PulseAudio users, use "pulse"
# For Jack/Jack2 users, use "jackplug"
# For ALSA users, you may use "default" for your primary card
# or you may use hw:# where # is the number of the card desired
MIXER="pulse"
[ -n "$(lsmod | grep pulse)" ] && MIXER="pulse"
[ -n "$(lsmod | grep jack)" ] && MIXER="jackplug"
MIXER="${3:-$MIXER}"

# The instance option sets the control to report and configure
# This defaults to the first control of your selected mixer
# For a list of the available, use `amixer -D $Your_Mixer scontrols`
SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
                  sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
                  head -n1
                )}"

# The second parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="${2:-5%}"
echo $STEP
#------------------------------------------------------------------------

capability() { # Return "Capture" if the device is a capture device
  amixer -D $MIXER get $SCONTROL |
    sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

volume() {
  amixer -D $MIXER get $SCONTROL $(capability)
}

#------------------------------------------------------------------------

case "$1" in
  mute) echo "Toggling mute"; amixer -q -D $MIXER sset $SCONTROL $(capability) toggle ;;
  up) echo "Increasing volume by $STEP"; amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}+ unmute ;;
  down) echo "Decreasing volume by $STEP"; amixer -q -D $MIXER sset $SCONTROL $(capability) ${STEP}- unmute ;;
esac

volume

