
# Attempting to fix 256 color issues with fbterm.
case "$TERM" in
  xterm*)
    export TERM=xterm-256color
    ;;
  linux)
    [ -n "$FBTERM" ] && export TERM=fbterm
    ;;
esac


source ~/.antigen.zsh

antigen use oh-my-zsh
antigen bundles <<EOBUNDLES
git
command-not-found
colored-man-pages

djui/alias-tips

zsh-users/zsh-autosuggestions
zsh-users/zsh-completions
zsh-users/zsh-syntax-highlighting
rupa/z
vi-mode
EOBUNDLES

# Setup theme.
antigen theme bhilburn/powerlevel9k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs battery time)

# Enable fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Setup fzf and its util functions
source ~/dotfiles/zsh/fzf.zsh

# Override environment variables
export BROWSER="w3m"

# Aliases
alias apps='sudo /usr/bin/software-center'
alias c=clear
alias d='$HOME/dotfiles/do'
alias g=googler
alias h='$HOME/pyenv/bin/howdoi -n 3 -c'
alias today='~/pyenv/bin/gcalcli agenda now 11:59pm --calendar $CALENDAR --detail_location --detail_description'
alias week='~/pyenv/bin/gcalcli agenda --calendar $CALENDAR'

# Keybindings
bindkey '^B' push-line-or-edit

# Finally, source any local config.
source ~/.zshrc.local
